// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwhw_7fYT1ibbGK2hRXPZwZFRYcX0B-bU',
    appId: '1:369125469743:web:ba429f39e02f899ea760da',
    messagingSenderId: '369125469743',
    projectId: 'ojolali-13037',
    authDomain: 'ojolali-13037.firebaseapp.com',
    storageBucket: 'ojolali-13037.appspot.com',
    measurementId: 'G-H4CX4SBMLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwpza3YRBOHyomKYjjXWAzH3aQfLnYe0U',
    appId: '1:369125469743:android:aac818b622090cdca760da',
    messagingSenderId: '369125469743',
    projectId: 'ojolali-13037',
    storageBucket: 'ojolali-13037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_T6eqN7fif1B8JzomqdWcP4g9Y5j6gQE',
    appId: '1:369125469743:ios:12ca86d3d4932e86a760da',
    messagingSenderId: '369125469743',
    projectId: 'ojolali-13037',
    storageBucket: 'ojolali-13037.appspot.com',
    iosClientId:
        '369125469743-tbfo2oia5f2lbebhv3281j652755v1bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_T6eqN7fif1B8JzomqdWcP4g9Y5j6gQE',
    appId: '1:369125469743:ios:12ca86d3d4932e86a760da',
    messagingSenderId: '369125469743',
    projectId: 'ojolali-13037',
    storageBucket: 'ojolali-13037.appspot.com',
    iosClientId:
        '369125469743-tbfo2oia5f2lbebhv3281j652755v1bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduleApp',
  );
}
